name: user ci 

            - nome: Super-Linter
  Você pode fixar o commit exato ou a versão.
  # usa: super-linter/super-linter@b92721f792f381cedc002ecdbb9847a15ece5bb8
  utiliza: super-linter/super-linter@v7.1.0

                      - nome: Configuração do Docker Compose
  Você pode fixar o commit exato ou a versão.
  # usa: docker/setup-compose-action@364cc21a5de5b1ee4a7f5f9d3fa374ce0ccde746
  usa: docker/setup-compose-action@v1.2.0
  com:
    # Versão do Compose. (ex.: v2.32.4)
    versão: # opcional
    # Armazenar em cache o binário do Compose no backend de cache do GitHub Actions
    cache-binary: # opcional, o padrão é verdadeiro
          
